import type { Metadata } from "next";
import { wantedSansVariables } from "./style/global.css";

export const metadata: Metadata = {
  title: "NextFantasy",
  description: "generated by pkw",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
